{% set name = "autovizwidget" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autovizwidget-{{ version }}.tar.gz
  sha256: 9816d2307c43f93c8107685c138f51a822e500b8e901f072a0d3e22b676a8869

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - hdijupyterutils >=0.6
    - ipywidgets >5.0.0
    - notebook >=4.2
    - pandas >=0.20.1
    - plotly >=3
    - python >=3.6

test:
  imports:
    - autovizwidget
    - autovizwidget/plotlygraphs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-incubator/sparkmagic/autovizwidget
  summary: 'AutoVizWidget: An Auto-Visualization library for pandas dataframes'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
