{% set name = "autovizwidget" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autovizwidget-{{ version }}.tar.gz
  sha256: e2e605b6f45736a6fefd43dcd275d69804293294d914f0903fd30265ac1b65a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - hdijupyterutils >=0.6
    - ipywidgets >5.0.0
    - notebook >=4.2
    - pandas >=0.20.1,<2.0.0
    - plotly >=3
    - python >=3.6

test:
  imports:
    - autovizwidget
    - autovizwidget.plotlygraphs
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/jupyter-incubator/sparkmagic/autovizwidget
  summary: 'AutoVizWidget: An Auto-Visualization library for pandas dataframes'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
    - devstein
