{% set name = "autovizwidget" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autovizwidget-{{ version }}.tar.gz
  sha256: daf3257c137cafba86ddc8271cd37c3783d3a958a0ff8111f40ea8de2139cf3a

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - hdijupyterutils >=0.6
    - ipywidgets >5.0.0
    - notebook >=4.2
    - pandas <3.0.0
    - plotly >=3
    - python >={{ python_min }}

test:
  imports:
    - autovizwidget
    - autovizwidget.plotlygraphs
  commands:
    - pip check || true
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-incubator/sparkmagic/autovizwidget
  summary: 'AutoVizWidget: An Auto-Visualization library for pandas dataframes'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
    - devstein
