{% set name = "autovizwidget" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autovizwidget-{{ version }}.tar.gz
  sha256: 562861e9aa25c460eb27b958031a50c008d4333179049357ff1fe25e80c07141

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - hdijupyterutils >=0.6
    - ipywidgets >5.0.0
    - notebook >=4.2
    - pandas <3.0.0
    - plotly >=3
    - python >={{ python_min }}

test:
  imports:
    - autovizwidget
    - autovizwidget.plotlygraphs
  commands:
    - pip check || true
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-incubator/sparkmagic/autovizwidget
  summary: 'AutoVizWidget: An Auto-Visualization library for pandas dataframes'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
    - devstein
