{% set name = "autovizwidget" %}
{% set version = "0.12.5" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d4bc1baac59de1713b5c0366d01be97910de5132ab9c0fe9e3c9e647f8720105" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
    run:
        - python
        - notebook >=4.2
        - ipywidgets >=5.0.0
        - hdijupyterutils >=0.6.0
        - plotly

test:
    imports:
        - autovizwidget

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
    license: BSD 3-clause
    summary: An Auto-Visualization library for pandas dataframes


extra:
  recipe-maintainers:
    - danielfrg
