{% set name = "autovizwidget" %}
{% set version = "0.13.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "5e2a64eb577a05cdb5019eca425590ac7d82ecaf5b0b089e5b377df0597d245c" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    noarch: python
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
    build:
        - python
        - pip
    run:
        - python
        - notebook >=4.2
        - ipywidgets >=5.0.0
        - hdijupyterutils >=0.6.0
        - plotly >=3

test:
    imports:
        - autovizwidget

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
    license: BSD 3-clause
    summary: An Auto-Visualization library for pandas dataframes


extra:
  recipe-maintainers:
    - danielfrg
