{% set name = "autovizwidget" %}
{% set version = "0.12.7" %}
{% set hash_type = "sha256" %}
{% set hash_val = "130e5de5bef9a63b86dba1c641d34aa7a0174b1eb729defef9e062b50677d0cd" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    noarch: python
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
    build:
        - python
        - pip
    run:
        - python
        - notebook >=4.2
        - ipywidgets >=5.0.0
        - hdijupyterutils >=0.6.0
        - plotly

test:
    imports:
        - autovizwidget

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/autovizwidget
    license: BSD 3-clause
    summary: An Auto-Visualization library for pandas dataframes


extra:
  recipe-maintainers:
    - danielfrg
