appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YvygrbceKu/gvhNPEmKQkQcm+nkNluzmV09jVHYHTAZzDql+wV2Fp89KOnE+v3zm2z3how32EuWVCFkl87csBC3agj6eVaXiJGUcInQs1Kk0ivNtdNcTqLBwCnyOrFFMAGq65D+F1ND3udTkDkRWe7QVzkCe+nUy4WMSKXJ7Wuoy+RlRxG/mHSnI1LVXPT9WBP75pxkZmxYrGPvWAewvhmBqn1hYoQ3t4ZelcRKkOwx2CA5toGBE5Gabi3QlIlHSQyDJXn/Zyg279wrYb2w4nSLUmfnuAabcPi+fHPzqCmMMogUZ1pYj1KRnIC9vZqKeo2kJPLX0z12jvMgR+Js7lfhYbxBeusnPlJwfBDWfTm4u2sg0GLGYjrv7u42W5TOjBlUipaLxFENF1IecdBXuycehp1Ba/+UZ3jiJYSIE6adLo2yrhrsulGW2FIWyLKHm99GMSPSSfVx4m0kO1d8+wQjaCLY1WA2gJCwfnAgft//mSFWl9WQ1GK9THc86LPvwxe5YfFDwnxWRjDaQMIiCbemhR6bOJw0jgMlUI4hCSNfLQN41Hy79oVGNTIJGjzNRjBZVk4Nsexo4BLZwt/mbwE0nNs5dF8IpgCx5/ivqshaXNscRrf7kB+m4UdQMDrTB3GDsglfXwdLkHWDelVSmGRqxUX4EpXJ3BHWjQE9QNyw=}
